version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.3-node-browsers

    steps:
      - checkout
#      - run: sudo apt install -y libpng-dev
#      - run: sudo apt install php-gd.x86-64

#      - run:
#        name: Install missing PHP Extensions
#        command: |
#          set +o pipefail
#          composer check-platform-reqs --no-ansi | grep missing | awk '{print $1}' | sed 's|^ext-||' | \
#          xargs -I@ sh -c 'sudo -E docker-php-ext-install @'
#          set -o pipefail
#
#      - restore_cache:
#              keys:
#                - v1-dependencies-{{ checksum "composer.json" }}
#                - v1-dependencies-

      - run: sudo docker-php-ext-install zip

      - run: sudo pecl channel-update pecl.php.net
      - run: sudo pecl install mongodb
      - run: echo 'extension=mongodb.so' | sudo tee /usr/local/etc/php/conf.d/mongodb.ini

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.json" }}
            - v1-dependencies-
      - run: composer install -n --prefer-dist

      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor
      - restore_cache:
          keys:
            - node-v1-{{ checksum "package.json" }}
            - node-v1-
      - run: yarn install
      - save_cache:
          key: node-v1-{{ checksum "package.json" }}
          paths:
            - node_modules

      # prepare the database
      # - run: touch storage/testing.sqlite
      # - run: php artisan migrate --env=testing --database=sqlite_testing --force

#      - run: cp .env.testing .env
      - run: ./vendor/bin/phpunit
      # - run: ./vendor/bin/codecept build
      # - run: ./vendor/bin/codecept run

  deploy-prod:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - add_ssh_keys;
      - run: ssh ${USER_NAME}@${HOST_NAME} 'cd JobEvaluationSystem && git pull'

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy-prod:
          requires:
            - build
          filters:
            branches:
              only: master
